### PR TITLE
Adds AVX512 support

### PR DESCRIPTION
**Pull request by RodneyGuo**
To enable AVX512 support:
  cmake -DOJPH_ENABLE_INTEL_AVX512=ON ..

### CODE REVIEW

**Comment by aous72** [comment]
Thank you Rodney for submitting this important addition.
I just want to check that it passes all tests before committing it in.
I currently do not have access to AVX512 machine, but I can emulate it.

Thank you again.

Kind regards,
Aous

**Comment by RodneyGuo** [comment]
Hi Aous,

The change passed the stress test with 1000+ images which have random width, height and data.
However, the stress test is only for 16 bit (2 byte) images with the following options: -num_decomps 5 -num_comps 1 -signed true -bit_depth 16 -downsamp \{1,1\}
The build-in test does not work for me. I got some failure during the compilation. I will spend some time to fix it, run the build-in test-cases and update the result.

BTW. the original commit has an issue in the CMakefile that will effect the non-AVX512 build. I updated the patch to fix this issue. Sorry for that.

**Comment by aous72** [comment]
I am sorry, but the test work I have done incomplete.  It only works on Linux.  
On other platforms, I need to fiddle with things to make it work.

It is fine to have issues that we can work on together.

Kind regards,
Aous.

**Comment by aous72** [comment]
Could you make your pull request against the development branch?
I can do this from my side, but I am not sure who should do this re-targeting.

I want to give you full credit for this, but I am not fully skilled with github. 

Cheers,
Aous.

**Comment by RodneyGuo** [comment]
done :)

**Comment by aous72** [comment]
Let's merge it then, and if you needed to modify anything then you can create a pull request.

Thank you.

**Comment by aous72** [comment]
Hi Rodney,

I did a few modifications to the AVX512 code to integrate it with the rest of the code; my plan was not to modify your code so long that it does not interfere with the rest of the code.

I added automatic detection for AVX512 support in the CPU; if the CPU supports it, the encoder path is included.

I faced some problems in that static parts of the AVX512 encoder code; they got executed even if the encoder path is not.  These are: left_shift and right_shift initializations and VLC tables initializations.

As you know I do not have AVX512 cpu, so errors issued an Illegal Instruction faults.  This is gone now.

I ran my test code using SDE, and it works.
The encoder currently is working for 64x64, 32x32,16x16 codeblocks.  
It fails for 4x4, 1024x4, 4x1024, 512x8, 8x512, and 256x16.
If you had the time, pickup my development branch and have a look.
Otherwise, I will have a look at some point.

To have the test path, inside ./build do
```
 cmake -DOJPH_BUILD_TESTS=yes ..
 make
 ctest  --output-on-failure
```

I need to spend the time to fully understand your code and figure out if anything needs to be fixed.
I should take care not to violate memory access.

Ideally, all the accelerated paths needs to be tested in github actions; they also need their own directives similar to the OJPH_ENABLE_INTEL_AVX512.

Thank you for this pull request.

Kind regards,
Aous.

**Comment by RodneyGuo** [comment]
Hi Aous,

I did a quick test in my setup. It showed a positive result. Here are the commands I used:
mkdir build
cd build
cmake -DOJPH_ENABLE_INTEL_AVX512=ON ..
make -j
cd ..
mkdir build_test
cd build_test
cmake -DOJPH_BUILD_TESTS=yes ..
make -j
ctest  --output-on-failure > result.log

The result.log is attached. The setup is now occupied and I will do further test tomorrow to make sure the AVX512 instruction is used in the test.

[result.zip](https://github.com/aous72/OpenJPH/files/11414776/result.zip)

**Comment by aous72** [comment]
All the tests have passed on your side.
Thank you.  
Looking forward for the check.
Also check that the AVX512 get used in
/src/others/ojph_arch.cpp line 140 and afterwards.  
This is where I check for AVX512 support. 
level should equal to X86_CPU_EXT_LEVEL_AVX512, which is 11.
I am checking if AVX512vl is available; maybe this is too much.

I am including the results I am getting.  This is emulating cannon lake; I got the same results with skylake server.
[test_results.log](https://github.com/aous72/OpenJPH/files/11414836/test_results.log)

**Comment by aous72** [comment]
I changed the check of AVX512VL to AVX512F, and pushed the code.

**Comment by RodneyGuo** [comment]
Not sure if this is the reason of the SEG Fault: Some instructions need AVX512CD support. Here is one of the example:

__m512i _mm512_mask_lzcnt_epi32 (__m512i src, __mmask16 k, __m512i a)
#include <immintrin.h>
Instruction: vplzcntd zmm {k}, zmm
CPUID Flags: AVX512CD

**Comment by aous72** [comment]
Usually "segmentation fault" is due to memory access issues.
Errors due to not existing instructions is usually "Illegal instruction" errors.
If you check my test_results.log, you see that SDE shows many unaligned accesses.  For example,
```
~/sde/sde64 -cnl -- ../../bin/ojph_compress -i ./jp2k_test_codestreams/openjph/references/Malamute.ppm -o ./simple_enc_rev53_4x4.j2c -reversible true -block_size "{4,4}"
 TID: 0 executed instruction with an unaligned memory reference to address 0x7fe8a4200b60 INSTR: 0x7fe8a9a5a1c5: IFORM: VMOVDQA64_ZMMu64_MASKmskw_MEMu64_AVX512 :: vmovdqa64 zmm0, zmmword ptr [rax]
	IMAGE:    /home/aous/OpenJPH/bin/libopenjph.so.0.10
	FUNCTION: _ZN4ojph5local28ojph_encode_codeblock_avx512EPjjjjjjS1_PNS_21mem_elastic_allocatorERPNS_11coded_listsE
	FUNCTION ADDR: 0x7fe8a9a59a94
SDE ERROR:  TID: 0 executed instruction with an unaligned memory reference to address 0x7fe8a4200b60 INSTR: 0x7fe8a9a5a1c5: IFORM: VMOVDQA64_ZMMu64_MASKmskw_MEMu64_AVX512 :: vmovdqa64 zmm0, zmmword ptr [rax]
	IMAGE:    /home/aous/OpenJPH/bin/libopenjph.so.0.10
	FUNCTION: _ZN4ojph5local28ojph_encode_codeblock_avx512EPjjjjjjS1_PNS_21mem_elastic_allocatorERPNS_11coded_listsE
	FUNCTION ADDR: 0x7fe8a9a59a94
```

It is an issue with stride?  Maybe line 60 in ojph_codeblock.cpp should be
```
ui32 stride = (nominal.w + 15) & ~15U; // a multiple of 16
```

Cheers,
Aous.

**Comment by aous72** [comment]
Yeah, I have to check lines 60 and 73 to get this working.
Now, we have three failures due to full MagSgn buffers:
50 - TestExecutables.SimpleEncIrv974x1024 (Failed)
52 - TestExecutables.SimpleEncIrv978x512 (Failed)
65 - TestExecutables.SimpleEncRev534x1024 (Failed)
This can be a memory overrun problem.

**Comment by RodneyGuo** [comment]
Hi Aous,

Yes, you are correct. As the encoder reads 32 bytes * 2 lines (512bits) for each iteration, the stride should be aligned to 32 bytes if AVX512 is enabled.

I just got the setup and I can also reproduce the issue from my side.
The reason I cannot reproduce yesterday is when I compiled with "cmake -DOJPH_BUILD_TESTS=yes ..", it overwrite the result compiled with"cmake -DOJPH_ENABLE_INTEL_AVX512=ON ..".
Now, I am trying the build with "cmake -DOJPH_BUILD_TESTS=yes -DOJPH_ENABLE_INTEL_AVX512=ON .."
I will check further the SEG fault and feedback the findings.

**Comment by aous72** [comment]
Thank you for the confirmation.

I pushed small modifications.  One to fix the stride issue, and one to add AVX512CD test.

At my PC, I am only having 
ojph error 0x00020005 at ojph_block_encoder_avx512.cpp:439: magnitude sign encoder's buffer is full
For example when I run ```~/sde/sde64 -cnl -- ../../bin/ojph_compress -i ./jp2k_test_codestreams/openjph/references/Malamute.ppm -o ./simple_enc_rev53_4x1024.j2c -reversible true -block_size "{1024,4}"```
Investigating further, one step ```ms_encode(msp, _cwd, _cwd_len);``` attempts to write 12582910 bytes to the buffer.

Github actions has two more types of errors, segmentation fault and bus error, which are very similar.
```
56/71 Test #56: TestExecutables.SimpleEncIrv9732x128 ................***Failed    0.19 sec
Note: Google Test filter = TestExecutables.SimpleEncIrv9732x128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestExecutables
[ RUN      ] TestExecutables.SimpleEncIrv9732x128
../../bin/ojph_compress -i ./jp2k_test_codestreams/openjph/references/Malamute.ppm -o ./simple_enc_irv97_32x128.j2c -qstep 0.01 -block_size "{128,32}"
Segmentation fault (core dumped)
/home/runner/work/OpenJPH/OpenJPH/tests/test_executables.cpp:122: Failure
```
and
```
65/71 Test #65: TestExecutables.SimpleEncRev534x1024 ................***Failed    0.21 sec
Note: Google Test filter = TestExecutables.SimpleEncRev534x1024
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestExecutables
[ RUN      ] TestExecutables.SimpleEncRev534x1024
../../bin/ojph_compress -i ./jp2k_test_codestreams/openjph/references/Malamute.ppm -o ./simple_enc_rev53_4x1024.j2c -reversible true -block_size "{1024,4}"
Bus error (core dumped)
/home/runner/work/OpenJPH/OpenJPH/tests/test_executables.cpp:122: Failure
```

Cheers,
Aous.

**Comment by RodneyGuo** [comment]
Hi Aous,
The illegal length is due to the overflow of the e_val_vec array. Currently, the encoder assume the width of the block is not longer than 64 * (4 bytes). So the size of the e_val_vec array is 3, which is (64 / 32 + 1). When the issue happens, I saw the width is 832 (808 aligned to 832). I do not remember why it is assumed. Let me recall...

**Pull request merged**
